apiVersion: v1
kind: Service
metadata:
  name: nodejs-todo-service
spec:
  selector:
    app: nodejs-todo
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
#Above wasn't here at all

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-todo
  labels:
    app: nodejs-todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-todo
  template:
    metadata:
      labels:
        app: nodejs-todo
    spec:
      containers:
      - name: nodejs-todo
        image: blueluke/practice:todo
        ports:
        - containerPort: 3000 #was 80