apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-todo-deployment
  labels:
    app: nodejs-todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-todo
  template:
    metadata:
      labels:
        app: nodejs-todo
    spec:
      containers:
      - name: nodejs-todo
        image: blueluke/practice:todo
        ports:
        - containerPort: 80